#!/bin/bash

sudo dhcpcd --renew
sudo apt-get update
sudo apt-get -y install wget ca-certificates
wget https://raw.githubusercontent.com/phoenixctms/install-debian/master/install.sh -O ~/install.sh
chmod 744 ~/install.sh
sudo ~/install.sh 2>&1 | tee ~/install.log

# Delete me
rm -f ~/phoenix_install